import os
import json
import logging
from typing import List
from pydantic import BaseModel, Field
from typing import Literal
from models.models import DetectionFinding

logger = logging.getLogger(__name__)

class AIAnalysisResponse(BaseModel):
    fault_classification: Literal["ENVIRONMENT_FAULT", "MODEL_HALLUCINATION", "COMPLIANCE_VIOLATION", "RESOURCE_DRAIN"] = Field(
        description="The categorization of the core system fault or behavioral anomaly."
    )
    analysis_breakdown: str = Field(
        description=(
            "A structured breakdown formatting the finding into three explicit sections. "
            "You MUST add a blank newline between each numbered point for readability:\n"
            "1. Observed Behavior: What the detector found.\n\n"
            "2. Potential Impact: Operational or financial risks.\n\n"
            "3. Suggested Review Action: High-level architectural remediation steps."
        )
    )
    remediation_strategy: str = Field(
        description="The generic architectural strategy or conceptual change required to resolve the issue without assuming platform APIs."
    )
    confidence: Literal["HIGH", "MEDIUM", "LOW"] = Field(description="The calculated certainty level of the AI diagnosis.")
    estimated_fix_time_minutes: int = Field(description="The approximate developer minutes needed to apply the fix.")


class AgentIntelligenceAnalyzer:
    """
    Orchestrates the AI Intelligence Layer. Takes compressed findings from detectors,
    queries Gemini via structured JSON outputs, and enriches findings in-place.
    """
    @staticmethod
    def enrich_findings(findings: List[DetectionFinding]) -> List[DetectionFinding]:
        if not findings:
            return findings

        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            logger.warning("GEMINI_API_KEY not found in environment. Skipping AI enrichment and falling back to templates.")
            return findings

        print(f"Passing {len(findings)} compressed anomalies to AI Intelligence Layer...")

        try:
            from google import genai
            from google.genai import types
            client = genai.Client(api_key=api_key)
        except ImportError:
            logger.error("google-genai SDK not installed. Run 'pip install google-genai'. Falling back.")
            return findings

        for finding in findings:
            # Enforce business label change on the fly for write-only secret asset mutations
            if finding.detector_name == "SecretAccessDetector" and "created/modified" in "".join(finding.evidence):
                finding.business_label = "Protected Configuration Modification"

            prompt_context = {
                "detector_name": finding.detector_name,
                "business_label": finding.business_label,
                "impact_target": finding.target,
                "incident_count": finding.count,
                "forensic_evidence": finding.evidence
            }

            try:
                response = client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=f"Interpret this telemetry footprint profile:\n{json.dumps(prompt_context)}",
                    config=types.GenerateContentConfig(
                        system_instruction=(
                            "You are an expert platform engineering diagnostic interpreter specializing in LLM application telemetry.\n\n"
                            "CRITICAL INSTRUCTION: You are NOT performing active detection. You are interpreting already-validated "
                            "findings generated by deterministic rules. You must not introduce new environmental facts, guess system context, "
                            "or claim unproven root causes. All statements must be entirely traceable to the supplied findings.\n\n"
                            "PLATFORM AGNOSTIC CONSTRAINT: Do not assume or reference any specific platform API, configuration file option, "
                            "SDK, product capability, or framework feature (e.g., do not invent pseudo-code function calls like 'workspace.set_allowed_paths').\n\n"
                            "Your remediation strategies and breakdowns must focus broadly on context management, task-specific scopes, directory exclusion rules, "
                            "or prompt design guidelines."
                        ),
                        response_mime_type="application/json",
                        response_schema=AIAnalysisResponse,
                        temperature=0.1
                    ),
                )

                ai_data = AIAnalysisResponse.model_validate_json(response.text)
                fault_category = ai_data.fault_classification
                if finding.detector_name == "RapidFileEnumerationDetector" and fault_category == "ENVIRONMENT_FAULT":
                    fault_category = "RESOURCE_DRAIN"

                # Inject the structured evidence mapping straight into the root cause target field
                finding.root_cause = ai_data.analysis_breakdown
                finding.remediation_command = ai_data.remediation_strategy
                finding.fault_classification = fault_category

            except Exception as e:
                logger.error(f"Failed to enrich finding {finding.detector_name}: {str(e)}.")

        return findings